import os
import subprocess

Import("env")

# Where we'll write the generated header file to
VERSION_H = os.path.join("Software", "src", "devboard", "utils", "version_autogen.h")

def git(*args):
    return subprocess.check_output(["git", *args], stderr=subprocess.DEVNULL).decode().strip()

def safe(value):
    """Escape a value for use inside a C string literal."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


# 1. Gather the raw data from the environment/repo

tag = None
ancestor_tag = None
sha = None
branch = None
github_org = None
github_repo = None
github_pr = None
github_pr_head_sha = None

try:
    tag = git("describe", "--tags", "--exact-match")
except subprocess.CalledProcessError:
    pass

try:
    ancestor_tag = git("describe", "--tags", "--abbrev=0")
except subprocess.CalledProcessError:
    pass

try:
    sha = git("rev-parse", "HEAD")
except subprocess.CalledProcessError:
    pass

try:
    b = git("rev-parse", "--abbrev-ref", "HEAD")
    if b and b != "HEAD":
        branch = b
except subprocess.CalledProcessError:
    pass

if repo_full := os.environ.get("GITHUB_REPOSITORY", "").strip():
    if "/" in repo_full:
        github_org, github_repo = repo_full.split("/", 1)

if pr := os.environ.get("GITHUB_PR", "").strip():
    github_pr = pr

if pr_head_sha := os.environ.get("GITHUB_PR_HEAD_SHA", "").strip():
    github_pr_head_sha = pr_head_sha


# 2. Compute BUILD_VERSION

if tag:
    build_version = tag
elif ancestor_tag and sha:
    short_sha = sha[:7]
    if github_pr and github_pr_head_sha:
        build_version = f"{ancestor_tag}dev-{github_pr_head_sha[:7]} (#{github_pr})"
    elif branch:
        build_version = f"{ancestor_tag}dev-{short_sha} ({branch})"
    else:
        build_version = f"{ancestor_tag}dev-{short_sha}"
else:
    build_version = "unknown"


# 3. Generate the header file

lines = [
    "#pragma once",
    "",
    "// AUTO-GENERATED by tools/identify_build.py — do not edit.",
    "",
]

def define(name, value):
    """Emit  #define NAME "value"  — omit entirely when value is None."""
    if value is not None:
        lines.append(f'#define {name} "{safe(value)}"')

define("GIT_TAG", tag)
define("GIT_ANCESTOR_TAG", ancestor_tag)
if sha:
    define("GIT_SHA", sha)
    define("GIT_SHORT_SHA", sha[:7])
define("GIT_BRANCH", branch)
define("GITHUB_ORG", github_org)
define("GITHUB_REPO", github_repo)
define("GITHUB_PR", github_pr)
define("GITHUB_PR_HEAD_SHA", github_pr_head_sha)
if github_pr_head_sha:
    define("GITHUB_PR_HEAD_SHORT_SHA", github_pr_head_sha[:7])

lines += [
    "",
    f'#define BUILD_VERSION "{safe(build_version)}"',
    "",
]

new_content = "\n".join(lines)


# 4. Write file only if changed

try:
    old_content = open(VERSION_H).read()
except (FileNotFoundError, IOError):
    old_content = ""

if old_content != new_content:
    with open(VERSION_H, "w") as f:
        f.write(new_content)
